default:
  image: python:bullseye

  before_script:
    - apt update -qy
    - apt install -y python3-pip
    - apt install -y python3-tk
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt

tests:
  stage: test
  script:
    - cd tests
    - python3 -m pip install -r test_requirements.txt
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
